export const ADD_PRODUCT_BASKET = "ADD_PRODUCT_BASKET";
export const GET_NUMBERS_BASKET = "GET_NUMBERS_BASKET";
export const QUANTITY_BASKET = "QUANTITY_BASKET";
export const REMOVE_PRODUCT_BASKET = "REMOVE_PRODUCT_BASKET";