export const ADD_PRODUCT_BASKET = "ADD_PRODUCT_BASKET";
export const GET_NUMBERS_BASKET = "GET_NUMBERS_BASKET";
export const QUANTITY_BASKET = "QUANTITY_BASKET";
export const REMOVE_PRODUCT_BASKET = "REMOVE_PRODUCT_BASKET";
export const RESET_BASKET = "RESET_BASKET";
export const RESET_ORDERS = "RESET_ORDERS";
export const ADD_ORDER = "ADD_ORDER";